package nestjs

type NestCliConfig struct {
	Schema          string `json:"$schema"`
	Collection      string `json:"collection"`
	SourceRoot      string `json:"sourceRoot"`
	CompilerOptions struct {
		DeleteOutDir bool   `json:"deleteOutDir"`
		Webpack      bool   `json:"webpack"`
		TsConfigPath string `json:"tsConfigPath"`
	} `json:"compilerOptions"`
	Monorepo bool                `json:"monorepo"`
	Root     string              `json:"root"`
	Projects map[string]*Project `json:"projects"`
}

type Project struct {
	Name string
	Rel  string

	// Default generated by nest cli
	Type            string `json:"type"`
	Root            string `json:"root"`
	EntryFile       string `json:"entryFile"`
	SourceRoot      string `json:"sourceRoot"`
	CompilerOptions struct {
		TsConfigPath string `json:"tsConfigPath"`
	} `json:"compilerOptions"`
}
